remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: UtilGDE
description: PÃ¡gina auxiliar para configurar UtilGDE
